### ISSUE TITLE
Add support to SQL

### ISSUE THREAD

**Issue by sukesh1999** [little-brother/sqlite-x#4]
Hi Sir, can you add support to reading from SQL server. 

It would be very helpful

**Comment by little-brother** [comment]
You can use [Total Commander](https://www.ghisler.com/download.htm) with [ODBC](https://github.com/little-brother/odbc-wlx)-plugin. You should create `dsn`-file by ODBC Data Source Administrator (`Win + R` > odbcad32) and then open it in Total Commander in its viewer by `F3`.
You can find more information in [a plugin Wiki](https://github.com/little-brother/odbc-wlx/wiki).

**Comment by sukesh1999** [comment]
hi @little-brother  thanks a lot for quick response. I would like to connect to MS SQL databases (instead of SQLLITE ) and do the following edit rows, add rows and delete rows. Your mentioned solution works, but i would like to know if its possible to make a easier setup like this repo.. Thanks again for the response.

**Comment by little-brother** [comment]
> edit rows, add rows and delete rows ... Your mentioned solution works

Just for viewing data, not editing. To edit data the SQL-database have to provide a row id that is used to [DML](https://en.wikipedia.org/wiki/Data_manipulation_language)-operation. Oracle and SQLite have `rowid` pseudo-column for that. Another databases such MSSQL, Postgres and MySQL don't have. Without this column is not easy to change data. Especially when table doesn't a primary key and you want to edit one of two equal rows.

I think you should use SSMS. Of course it;'s not a lighweight software but fully robust.
