### ISSUE TITLE
Would you consider any further development as a data entry tool?

### ISSUE THREAD

**Issue by Gavin-Holt** [little-brother/sqlite-x#5]
Hi,

This is so quick and easy, it's fantastic - thank you.

Would you consider any further development as a data entry tool?

I work in the UK National Health Service, and like many organisations we ask unskilled staff to collect data in Excel with no validation rules! Garbage in garbage out - is the inevitable result. Trying to create validation is hampered by the limited functionality in our old version of Excel 2016.

sqlite-x looks like a great starting point for a dedicated data entry application, unfortunately I don't have the skills to install or use a compiler. However, with the greatest respect, I would offer a design for an ideal application:

1. Menus to help users discover functionality[1].

![image](https://github.com/little-brother/sqlite-x/assets/5831149/90b4549e-95ae-4b7a-8bb3-89574a831e70)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/a5011c9b-c20b-414b-9a24-01dfb29ee67d)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/a2f2a9f3-09c3-4bdf-bbdb-06b9fc45c52a)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/e2ebcaff-bc6b-4d5d-97c2-9493beac73fa)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/b1c26fd2-4287-47d6-befa-d0f5deda9c68)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/a8c1e1d0-c8ea-410d-ae56-993d0e73bb8a)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/588bb27b-5240-4129-b6fd-4d95f2e6f970)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/316920d8-2cb1-45d5-99e2-5a365e7e0321)

3. More keyboard shortcuts 
    Data entry is much quicker with less mouse work.

5. Default values.
    Currently, DEFAULT values are not entered when inserting a new row.

6. Validation rules at field and record level.
    Currently, CHECK statements in my databases are ignored.
    Msgbox on error showing first validation rule broken.
    A popup editor for CHECK statements (I think it's not easy to update CHECK constraints).
    Built-in functions to validate against live query of the database [2], creating a LIST data type.
    Built-in functions to validate dates [3] are real, and then date calculations as validation functions [4]

7. Added functionality (in the order it appears in the menus)
    Table|Export as csv, xls, xlsx
    View|Open file dialog to saved SELECT - sql
    View|Save file dialog to save current SELECT - sql
    View|Export as csv, xls, xlsx
    Column|Filter show filters and place cursor in the filter for current column
    Column|Sort sort or reverse sort, accessible from keyboard and menu
    Column|Validation rules - see above
    Row|Template file dialog to insert a saved row - csv
    Row|Save file dialog to save current row - csv
    Row|Validation rules - see above
    Edit|Search finds a match (allow %_) in any field to quickly navigate

8. Added usability
    Insert row popup, no bigger than screen height - scroll bars if necessary.
    Insert row popup, allow resizing - remember size/position.
    Insert row fields, widgets by type - need to detect booleans, dates and lists - perhaps from validation rules.

    - INTEGER. Right aligned. Increment and decrement with  Ctrl+Up Ctrl+Dn.
    - REAL. Right aligned, default two decimals. Increment and decrement with Ctrl+Up Ctrl+Dn.
    - TEXT. Text box grows in height with size of contents. Spellchecking would be in the paid version! 
    - BOOLEANS. Check box. Space to toggle.
    - DATES. Use locale long format. Next and previous with Ctrl+Up Ctrl+Dn. Validate as real date, then apply column/row validation rules.
    - LISTS. Fuzzy matching auto-complete as you type drop down/up (depending of screen position) [5].

Kind Regards Gavin Holt 

[1] Proposed menus and shortcut keys

These IDM numbers are all wrong - sorry

10000 MENU
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
{
POPUP "&Database"
{
	MENUITEM "&Open\tCtrl+O",  501
	MENUITEM SEPARATOR
	MENUITEM "Recent",  500
	MENUITEM "E&xit\tESC",  522
}
POPUP "&Table"
{
	MENUITEM "&New\tCtrl+N",  800
	MENUITEM "&Export as..\tCtrl+E",  801
}
POPUP "&Views"
{
	MENUITEM "&Open..\tCtrl+Q",  801
	MENUITEM "&Save..\tCtrl+Alt+Q",  801
	MENUITEM "&Export as..\tCtrl+Alt+E",  801
}
POPUP "&Column"
{
	MENUITEM "&Filter\tCtrl+F",  800
	MENUITEM "&Sort\tCtrl+S",  800
	MENUITEM SEPARATOR
	MENUITEM "&Copy\tCtrl+Shift+C",  800
	MENUITEM SEPARATOR
	MENUITEM "&Hide\tCtrl+Shift+H",  801
	MENUITEM "&UnHide all\tCtrl+Space",  801
	MENUITEM SEPARATOR
	MENUITEM "&Validation rules...\tCtrl+R",  801
}
POPUP "&Row"
{
	MENUITEM "&Insert\tIns",  801
	MENUITEM "&Template..\tCtrl+T",  801
	MENUITEM "&Save..\tCtrl+Alt+T",  801
	MENUITEM SEPARATOR
	MENUITEM "&Delete\tDel",  801
	MENUITEM SEPARATOR
	MENUITEM "&Copy\tCtrl+Alt+C",  800
	MENUITEM SEPARATOR
	MENUITEM "&Validation rules...\tCtrl+Alt+R",  801
}
POPUP "&Edit"
{
	MENUITEM "&Edit cell\tF2",  603
	MENUITEM SEPARATOR
	MENUITEM "&Undo\tCtrl+Z",  601
	MENUITEM "&Redo\tCtrl+Shift+Z",  602
	MENUITEM SEPARATOR
	MENUITEM "Cu&t\tCtrl+X",  603
	MENUITEM "&Copy\tCtrl+C",  604
	MENUITEM "&Paste\tCtrl+V",  605
	MENUITEM "&Delete\tDel",  606
	MENUITEM SEPARATOR
	MENUITEM "Select &All\tCtrl+A",  607
	MENUITEM SEPARATOR
	MENUITEM "&Search\tCtrl+S",  610
	MENUITEM "Search &Next\tF3",  611
	MENUITEM "Search &Previous\tShift+F3",  612
}
POPUP "&Settings"
{
	MENUITEM "&Font",  700
	MENUITEM "&Zoom\tCtrl+Mouse Wheel",  701
	MENUITEM SEPARATOR
	MENUITEM "&Headers",  704
	MENUITEM "&Filters",  704
	MENUITEM SEPARATOR
	MENUITEM "&Light theme\tCtrl+L",  704
	MENUITEM "&Dark theme\tCtrl+D",  704
	MENUITEM SEPARATOR
	MENUITEM "&Edit settings",  702
}
POPUP "&Help"
{
	MENUITEM "&Wiki",  1102
	MENUITEM "&Home page",  1102
	MENUITEM "&SQLite help",  1102
	MENUITEM SEPARATOR
	MENUITEM "&About",  1101
}
}

[2] Sorry my SQLite is not good enough to solve this. What I want is to validate against the same list used to populate the widget. Adding to the validation source table e.g Surgeon Name. Should mean this option appears immediately in the widget (i.e don't generate value lists at initialisation).

[3] https://www.sqlite.org/forum/info/a1414bf570006db8

[4] https://www.sqlite.org/lang_datefunc.html

[5] This is not a standard textbox/listbox/combobox, auto-complete "where target  contains input string" would be ok, auto-complete "where target begins with input string" is not very useful. My favourite fzf.exe fuzzy matching  https://github.com/junegunn/fzf. I just want to type and then press tab to move on, no extra keys to activate drop down/up.

**Comment by little-brother** [comment]
Hi Gavin,

**sqlite-x** is a **simple** viewer and editor for SQLite and that's all. There is no plan to extend it to a data entry tool. 
You should check [Valentina Studio](https://www.valentina-db.com/en/valentina-studio-overview). It has configurable input forms.

I suppose that you move in a wrong direction with a desktop app because you attach yourself to OS and will have work with keep the app in up-to-date state. I see two alternatives.
1. The special site with input forms serviced by one central web-server.
2. If some users haven't a direct connection to one server and they have to send xls/csv-files by e-mail then it may be a server that reads e-mails, parse input files, adds valid rows to a database and send back rejected rows.
    In my opinion, Excel is a good choice for input data when you work with remote users (just provide to users a recommended/mandatory format to unify input).

If you want to continue the discussion then I would prefer to do it by e-mail <a href="mailto:lb.im@ya.ru?subject=UK National Health Service">lb.im@ya.ru</a>.

> in our old version of Excel 2016

My Excel 2003 has an even longer beard and for me it's fine :D



> Currently, DEFAULT values are not entered when inserting a new row.

So, it's a bug and it should be fixed. Thanks.

**Comment by Gavin-Holt** [comment]
Hi

Many thanks for your pointer to Valentina, I will have a good look. 

The NHS is 100% PC/Windows, for better or worse. A server/client model would have many advantages, but there are so many changing requirements to gather data, I doubt we would get any funding for bespoke web based solutions.

I have tried in Excel, but the validate conditional drop down combo box, is a real pain for the user [1]. It won't autocomplete - so you have to click/search/click or type the **whole** string. I don't have permission to use VBA. 

Look forward to a bug fix at some point.

Kind Regards Gavin Holt 

[1] https://exceljet.net/formulas/data-validation-with-conditional-list

**Comment by little-brother** [comment]
You can describe on email what you need exactly and how you are going to use it. Maybe I can make it as a 2-5 day free project if it's simple.
Develop an editor for an arbitrary database is much harder than for a special case.
