### ISSUE TITLE
Font name in settings (ini file) appears to be ignored

### ISSUE THREAD

**Issue by dbaron4** [little-brother/sqlite-x#6]
I changed the font to several different ones but it always appears to be Arial which it started out as.

**Comment by little-brother** [comment]
What is your system language? Maybe ini-file should have charset option too. sqlite-x always uses `ANSI_CHARSET`.
`font=Comic Sans MS` works fine for cyrilic.

Please test this version [sqlite-x.zip](https://github.com/little-brother/sqlite-x/files/13310431/sqlite-x.zip) with DEFAULT_CHARSET.

**Comment by dbaron4** [comment]
It works! Thanks. That was fast.

**Comment by little-brother** [comment]
Ok. It will be fixed in the next release.

Thanks for your report - it was a common mistake in all my TC plugins.

**Comment by little-brother** [comment]
Fixed.
