### ISSUE TITLE
Ctrl+F is making the Add Table button resize

### ISSUE THREAD

**Issue by Gavin-Holt** [little-brother/sqlite-x#7]
Hi

Many thanks for version 1.0.3, I am enjoying the new functionality.

However, unlike 1.0.2 the Ctrl+F shortcut has a side effect - it resizes the Add Table Button.

Before Ctrl+F
<img width="600" alt="sshot-033" src="https://github.com/little-brother/sqlite-x/assets/5831149/ef9aab50-60f1-4bb2-b7b3-074692f65db3">

After Ctrl+F
<img width="600" alt="sshot-034" src="https://github.com/little-brother/sqlite-x/assets/5831149/7bc8e93d-229a-455a-b994-2786861ac0aa">

After another Ctrl+F
<img width="600" alt="sshot-035" src="https://github.com/little-brother/sqlite-x/assets/5831149/d50d478d-444c-4d18-9fdf-837cd249b931">

Sorry I have no idea why.

Kind Regards Gavin Holt

**Comment by little-brother** [comment]
Fixed.
