### ISSUE TITLE
Shift+TAB no longer works in new row dialog box

### ISSUE THREAD

**Issue by Gavin-Holt** [little-brother/sqlite-x#8]
Hi,

Many thanks for version 1.0.3, I am enjoying the new functionality. 

The ability to press ```TAB``` during autocompletion is great - selection and it moves me to the next field. This avoids multiple key presses and especially avoids using ```ENTER```  -  brilliant. 

However, unlike 1.0.2 I can't navigate to the previous field using ```Shift+TAB```.  If this is easy to fix it would provide consistency with normal dialog box events.

Kind Regards Gavin Holt

**Comment by little-brother** [comment]
Hmm, I don't know about `Shift + TAB`. That is why `Ctrl + Tab` was implemented in the entire application.
I changed the shortcut to `Shift + TAB` to match default Windows behavior.
