### ISSUE TITLE
[Feature Request]: Paged, maximized data entry form

### ISSUE THREAD

**Issue by Gavin-Holt** [little-brother/sqlite-x#9]
Hi,

I am very grateful to you for providing, and amending, this software. Especially as you are busy working on another similar project.  My use-case is to design sqlite databases, and ask less computer-literate colleagues to enter data. 

One key attraction is sqlite's built in data validation, and using foreign key constraints is a very helpful mechanism. This is especially useful as you kindly built autocompletion into sqlite-x for data entry.

My one remaining problem is the size of the data entry screen.:

- Width of the field name is OK, but field text width is troublesome, as we have some long field entries that only differ at the end.
- Height is causing difficulties - I struggle to use tables with more than 26 fields (old eyes: font 22, monitor @125%) .

I understand there are severe restrictions when using vanilla win32 C code (i.e, no scroll bars, no easy window/field resizing).

Would you be able to paginate data entry, the same way the [CSVViewer tool from nirsoft](https://www.nirsoft.net/utils/csv_file_view.html) deals with numerous fields?

![image](https://github.com/little-brother/sqlite-x/assets/5831149/feb0aefe-1b6f-4962-b34b-dadc0dcb95db)

![image](https://github.com/little-brother/sqlite-x/assets/5831149/d6e2f1dc-d312-4d99-8f14-c42c9c04bda2)

The CSVViewer data entry form, detects screen height, and sets the height as large as possible - then offers additional pages for overflow. 

It does also have width resizing, simply growing all field text boxes to the right (not repaginating). 

This must be fiddly, so just max screen width (and height) would be a simple compromise.

I would love to hear how your other project is progressing.

Kind Regards Gavin Holt 

PS These data examples are off the internet - I can't risk using real data.

[dummy.csv](https://github.com/little-brother/sqlite-x/files/13833217/dummy.csv)

**Comment by little-brother** [comment]
Hi, Gavin,
Sorry for a long delay. I struggled with a scroll. It's a terrible tedios thing, so it was hard :)

Please test [pre-release version](https://github.com/little-brother/sqlite-x/files/13929518/sqlite-x.zip).
The next changes were made for `Add row`-dialog: 
- You can change the window size. The initial size is defined by a parent grid and a fields count.
- If you maximize the dialog window then it is opened maximized in the next time. The state is saved in ini-file.
- If there is no enough space for input filelds, then a vertical scroll appears. The scroll has some bugs. I hope it will be is not very critical for you. 

> I would love to hear how your other project is progressing.

Yes, it's in progress but very slowly :(

**Comment by Gavin-Holt** [comment]
Dear Andrey,

Once again I am very grateful. The scrolling/resizing data entry dialog is exactly what I wished for - thank you.

I am very happy to use it as it is - but after testing would humbly offer the following feedback about aesthetics:

1. The form does not follow the selected color theme, although the drop down list do, which looks odd.
2. Beyond the upper and lower limits, (i.e. < the first and > last field) further scrolling causes a flicker. I guess the form is redrawing  - when it does not need to.

Many Thanks

Kind Regards Gavin Holt

**Comment by little-brother** [comment]
Done.

1. The color for input fields was fixed.
2. The redundant redraw was removed.
